apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app
  namespace: health-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-system
  template:
    metadata:
      labels:
        app: core-system
    spec:
      containers:
      - name: app
        image: nginxdemos/hello:plain-text # Placeholder seguro
        ports:
        - containerPort: 80